/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DietRouteImport } from './routes/diet'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as PrescriptionRouteImport } from './routes/prescription'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SymptomsRouteImport } from './routes/symptoms'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DietRoute = DietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionRoute = PrescriptionRouteImport.update({
  id: '/prescription',
  path: '/prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomsRoute = SymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/diet': typeof DietRoute
  '/hospitals': typeof HospitalsRoute
  '/pharmacy': typeof PharmacyRoute
  '/prescription': typeof PrescriptionRoute
  '/privacy': typeof PrivacyRoute
  '/symptoms': typeof SymptomsRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/diet': typeof DietRoute
  '/hospitals': typeof HospitalsRoute
  '/pharmacy': typeof PharmacyRoute
  '/prescription': typeof PrescriptionRoute
  '/privacy': typeof PrivacyRoute
  '/symptoms': typeof SymptomsRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/diet': typeof DietRoute
  '/hospitals': typeof HospitalsRoute
  '/pharmacy': typeof PharmacyRoute
  '/prescription': typeof PrescriptionRoute
  '/privacy': typeof PrivacyRoute
  '/symptoms': typeof SymptomsRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/diagnostics'
    | '/diet'
    | '/hospitals'
    | '/pharmacy'
    | '/prescription'
    | '/privacy'
    | '/symptoms'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/diagnostics'
    | '/diet'
    | '/hospitals'
    | '/pharmacy'
    | '/prescription'
    | '/privacy'
    | '/symptoms'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/diagnostics'
    | '/diet'
    | '/hospitals'
    | '/pharmacy'
    | '/prescription'
    | '/privacy'
    | '/symptoms'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  DietRoute: typeof DietRoute
  HospitalsRoute: typeof HospitalsRoute
  PharmacyRoute: typeof PharmacyRoute
  PrescriptionRoute: typeof PrescriptionRoute
  PrivacyRoute: typeof PrivacyRoute
  SymptomsRoute: typeof SymptomsRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet': {
      id: '/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof DietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription': {
      id: '/prescription'
      path: '/prescription'
      fullPath: '/prescription'
      preLoaderRoute: typeof PrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptoms': {
      id: '/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof SymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  DietRoute: DietRoute,
  HospitalsRoute: HospitalsRoute,
  PharmacyRoute: PharmacyRoute,
  PrescriptionRoute: PrescriptionRoute,
  PrivacyRoute: PrivacyRoute,
  SymptomsRoute: SymptomsRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
