export type Lang = "en" | "ur";

export const dict = {
  brand: { en: "SehatSaathi AI", ur: "صحت ساتھی AI" },
  nav_home: { en: "Home", ur: "ہوم" },
  nav_diagnostics: { en: "Diagnostics", ur: "تشخیص" },
  nav_symptoms: { en: "Symptoms", ur: "علامات" },
  nav_diet: { en: "Diet Plan", ur: "غذائی پلان" },
  nav_pharmacy: { en: "Pharmacy", ur: "فارمیسی" },
  nav_scan: { en: "Prescription Scan", ur: "نسخہ اسکین" },
  nav_chat: { en: "Chat", ur: "چیٹ" },
  nav_hospitals: { en: "Hospitals", ur: "ہسپتال" },
  sign_in: { en: "Sign In", ur: "سائن ان" },
  sign_up: { en: "Sign Up", ur: "اکاؤنٹ بنائیں" },
  hero_title: { en: "Your Personal AI Healthcare Companion", ur: "آپ کا ذاتی AI ہیلتھ کیئر ساتھی" },
  hero_sub: {
    en: "24/7 AI-powered health monitoring — scan analysis, symptom insights, diet plans and medicines delivered to your door.",
    ur: "چوبیس گھنٹے AI کی مدد سے صحت کی نگرانی — اسکین کا تجزیہ، علامات کی جانچ، غذائی پلان اور ادویات آپ کے دروازے پر۔",
  },
  cta_diagnosis: { en: "Start Free Diagnosis", ur: "مفت تشخیص شروع کریں" },
  cta_medicines: { en: "Order Medicines", ur: "ادویات آرڈر کریں" },
  features_title: { en: "Everything your health needs, in one place", ur: "آپ کی صحت کی ہر ضرورت، ایک جگہ" },
  how_title: { en: "How it works", ur: "یہ کیسے کام کرتا ہے" },
  cart: { en: "Your Cart", ur: "آپ کی ٹوکری" },
  checkout: { en: "Proceed to Checkout", ur: "چیک آؤٹ کریں" },
  total: { en: "Total", ur: "کل" },
  empty_cart: { en: "Your cart is empty.", ur: "آپ کی ٹوکری خالی ہے۔" },
  add_to_cart: { en: "Add to Cart", ur: "ٹوکری میں ڈالیں" },
  quick_links: { en: "Quick Links", ur: "فوری روابط" },
  emergency: { en: "24/7 Emergency", ur: "چوبیس گھنٹے ایمرجنسی" },
  terms: { en: "Terms of Service", ur: "شرائط و ضوابط" },
  privacy: { en: "Privacy Policy", ur: "پرائیویسی پالیسی" },
  disclaimer: {
    en: "Generated by AI. Please consult a doctor.",
    ur: "AI سے تیار کردہ۔ براہ کرم ڈاکٹر سے مشورہ کریں۔",
  },
} as const;

export type DictKey = keyof typeof dict;

export const translate = (key: DictKey, lang: Lang) => dict[key][lang];
